name: CI-iOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15

    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v4

    - name: Select Latest Xcode
      run: |
        # Find the latest Xcode installed in /Applications
        LATEST_XCODE=$(ls /Applications | grep ^Xcode | sort -V | tail -n1)
        echo "Switching to $LATEST_XCODE"
        sudo xcode-select -switch "/Applications/$LATEST_XCODE"

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test
      run: |
        # Get the latest available iOS simulator runtime
        LATEST_RUNTIME=$(xcrun simctl list runtimes | grep 'iOS' | grep -v 'unavailable' | sort -V | tail -n1 | awk -F '[()]' '{print $2}')
        echo "Using latest iOS runtime: $LATEST_RUNTIME"
        xcodebuild clean build test \
          -project EssentialFeed/EssentialFeed.xcodeproj \
          -scheme "CI_iOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,OS=$LATEST_RUNTIME,name=iPhone 16 Pro"
